import Nav from './components/Nav/page'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from './nexttoast'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Blogging App</title>
      </head>
      <body className={inter.className}>
        <>
          <ToastContainer />
          <Nav />
          {children}
        </>
      </body>
    </html>
  )
}
